const facilities = [
    {name: 'KP-107', type: 'room', free: true,bookedBy:''},
    {name: 'KP-102', type: 'room', free: true,bookedBy:''},
    {name: 'KP-210', type: 'room', free: true,bookedBy:''},
    {name: 'KP-303', type: 'room', free: true,bookedBy:''},
    {name: 'KP-307', type: 'room', free: true,bookedBy:''},
    {name: 'KP-106', type: 'room', free: true,bookedBy:''},
    {name: 'KP-206', type: 'room', free: true,bookedBy:''},
    {name: 'KP-407', type: 'room', free: true,bookedBy:''},
    {name: 'KP-406', type: 'room', free: true,bookedBy:''},
    {name: 'R-1', type: 'room', free: true,bookedBy:''},
    {name: 'R-2', type: 'room', free: true,bookedBy:''},
    {name: 'R-3', type: 'room', free: true,bookedBy:''},
    {name:'Ground Floor Lab', type: 'lab', free: true,bookedBy:''},
    {name:'First Floor Lab', type: 'lab', free: true,bookedBy:''},
    {name:'Second Floor Lab', type: 'lab', free: true,bookedBy:''},
    {name:'Temenos Floor Lab', type: 'lab', free: true,bookedBy:''},
    {name: 'Projector1', type: 'projector', free: true,bookedBy:''},
    {name: 'Projector2', type: 'projector', free: true,bookedBy:''},
    {name: 'Projector3', type: 'projector', free: true,bookedBy:''},
];
module.exports = facilities;